name: MIHIR PATEL
description: Throughout my career, I have worked on diverse projects spanning web development, mobile applications, and software architecture. 
             I am well-versed in multiple programming languages such as Python, JavaScript, and Java, and have experience with frameworks and 
             technologies like React, Node.js, and Django.
theme: jekyll-theme-cayman


